[project]
name = "tumor-scan-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "torch",
    "torchvision",
    "torchinfo>=1.8.0",
    "ultralytics",
    "pillow",
    "opencv-python-headless"
]

[tool.vercel]
entrypoint = "webAPI:app"

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }